"""followers

Revision ID: 03913c8ab640
Revises: 2b778bb7799f
Create Date: 2020-04-02 19:48:43.917693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03913c8ab640'
down_revision = '2b778bb7799f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
